default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # The & is used to allow assets:precompile with no credentials
  host: <%= Rails.application.credentials&.database&.host %>
  username: <%= Rails.application.credentials&.database&.username %>
  password: <%= Rails.application.credentials&.database&.password %>


development:
  <<: *default
  database: jacson_dev_development

test:
  <<: *default
  database: jacson_dev_test

production:
  primary: &primary_production
    <<: *default
    database: jacson_dev_production
  cache:
    <<: *primary_production
    database: jacson_dev_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: jacson_dev_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: jacson_dev_production_cable
    migrations_paths: db/cable_migrate
